### ISSUE TITLE
Mistake in exercise 3.2.8

### ISSUE THREAD

**Issue by ncfavier** [andrejbauer/notes-on-realizability#14]
The maps are going the wrong way: we want Γ ⊣ ∇, not ∇ ⊣ Γ.

**Comment by andrejbauer** [comment]
Closed by 08524ce5921c1a0997d53e38db46c294a2a75a8b already.

**Comment by andrejbauer** [comment]
Closed by https://github.com/andrejbauer/notes-on-realizability/commit/08524ce5921c1a0997d53e38db46c294a2a75a8b already.
